name: Android Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 拉代码
        uses: actions/checkout@v4

      - name: 安装 Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: 给 gradlew 权限
        run: chmod +x gradlew

      - name: 编译 APK
        run: ./gradlew assembleDebug

      - name: 上传 APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: app/build/outputs/apk/debug/*.apk
